# Generated by Django 4.1.7 on 2024-04-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0003_series_cover_series_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volume',
            name='synopsis',
            field=models.TextField(max_length=300),
        ),
    ]
