# Generated by Django 4.1.7 on 2024-04-04 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0004_alter_volume_synopsis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='desc',
            field=models.TextField(default='-', max_length=500),
        ),
        migrations.AlterField(
            model_name='volume',
            name='synopsis',
            field=models.TextField(max_length=500),
        ),
    ]
