# Generated by Django 4.1.7 on 2024-04-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theapp', '0005_alter_series_desc_alter_volume_synopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='volume',
            name='pub_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
